# Generated by Django 3.2.6 on 2022-01-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinepost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='check',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
